version: '3.3'

volumes:
  pg-data:

services:
  postgres-local:
    image: postgres:16.3
    container_name: postgres-biblio-local
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/pg-data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - PGDATA=/pg-data
