version: '3.3'

volumes:
  pg-data:

services:
  biblio-app:
    image: ghcr.io/loicbefve/biblio-api:latest
    container_name: biblio-app
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=biblio-db
    env_file:
      - .env
    depends_on:
      - biblio-db
    volumes:
      - ${FICHES_PATH}:${FICHES_PATH}
  biblio-db:
    image: postgres:16.3
    container_name: biblio-db
    restart: always
    shm_size: 256mb
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
    env_file:
      - .env
